### ISSUE TITLE
US Driving licence

### ISSUE THREAD

**Issue by lanetteam-bhavin** [PDF417/pdf417-android#1]
Hi,
We are integrate pdf417 in our project to scan US driving license but it is not scanning though it is in pdf417 format. any lead or should we purchase license for it ?

Thanks,
Bhavin

**Comment by rmhrisk** [comment]
@DoDoENT can you explain how it is you regenerated the same barcode for @lanetteam-bhavin? Was it through any sort of image manipulation (sharpening, etc?)

**Comment by DoDoENT** [comment]
@rmhrisk I used [this barcode generator](http://www.racoindustries.com/barcodegenerator/2d/pdf417.aspx)
