### ISSUE TITLE
Options page does not apply immediately

### ISSUE THREAD

**Issue by postpersonality** [PDF417/pdf417-android#11]
8x18, 8x32, 12x26, 12x36, 16x36, 16x48

**Comment by DoDoENT** [comment]
Hi. DataMatrix support is only rudimentary and large data matrix codes are not well supported. Please attach problematic barcodes so we could analyze them and improve future version of SDK.

**Comment by postpersonality** [comment]
![dmtxcgid](https://cloud.githubusercontent.com/assets/2012215/9110346/9679f5be-3c45-11e5-9c6a-405fc053b67c.png)

**Comment by DoDoENT** [comment]
Are you sure that it does not work? I've just scanner the code you've posted with our [PlayStore app](https://play.google.com/store/apps/details?id=mobi.pdf417) and it worked: barcode content is: DEMO1234567

You just have to position the code right in the middle of the screen and align it with device. Rotation and perspective detection for DataMatrix is not implemented.

**Comment by postpersonality** [comment]
That's strange. Because yesterday it is not worked. Maybe options page does no apply immediately?

**Comment by DoDoENT** [comment]
Are you trying with our PlayStore app or within your app that integrated our SDK? What device are you using?

**Comment by postpersonality** [comment]
Yes, it is an options page.
1) Clean flag "datamatrix"
2) Close options page (back)
3) Kill app
4) Run app
5) Check flag "datamatrix"

**Comment by postpersonality** [comment]
Yes, I am trying PlayStore app (last version).

**Comment by postpersonality** [comment]
But that's strange, because square datamarix worked fine.

**Comment by DoDoENT** [comment]
I've just tried your steps and wasn't able to reproduce the issue. Option page applied immediately.

**Comment by postpersonality** [comment]
Me too. Ok. I'm closing an issue.

**Comment by DoDoENT** [comment]
I think this is just because that rectangular data matrix is more difficult to scan than a rectangular one. As I said earlier, this is because our DataMatrix support is only rudimentary (it uses ZXing internally, without our code).

**Comment by postpersonality** [comment]
Do you mean square one?

**Comment by DoDoENT** [comment]
Yes, sorry.
