### ISSUE TITLE
Gradle cannot expand LibRecognizer.AAR file

### ISSUE THREAD

**Issue by shepherdsiduli** [PDF417/pdf417-android#16]
Hi

"I have been trying to upgrade pdf417 library from version 4 to version 5.5 the current latest, unfortunately Gradle cannot expand the file I get the following error 

:app:prepareInfinityLibRecognizerUnspecifiedLibrary FAILED
Error:Execution failed for task ':app:prepareInfinityLibRecognizerUnspecifiedLibrary'.

> Could not expand ZIP 'C:\Users\xxxxx\AndroidStudioProjects\V2\xxx\LibRecognizer\LibRecognizer.aar'. "

**Comment by DoDoENT** [comment]
Hi,

can you try the [Maven integration](https://github.com/PDF417/pdf417-android#mavenIntegration)? It should be much easier than directly integrating LibRecognizer.aar.

**Comment by i1E** [comment]
Hi @shepherdsiduli,

have you successfully upgraded your app to the newer version of the pdf417 SDK? Can we close the issue?
