### ISSUE TITLE
Memory leak from RecognitionProcessCallback

### ISSUE THREAD

**Issue by xlsior** [PDF417/pdf417-android#17]
RecognitionProcessCallback in Recognizer singleton holds on to the MetadataListener reference even after calling terminate().

(We are on lib v5.3.0)

**Comment by DoDoENT** [comment]
Thanks for reporting that. We will fix that ASAP.

**Comment by DoDoENT** [comment]
This should be fixed in v5.5.1 which will be released next week.

**Comment by i1E** [comment]
This is fixed in v5.5.1 which is released

**Comment by i1E** [comment]
This is fixed in v5.5.1 which is released
