### ISSUE TITLE
Pdf417ScanActivity not working correctly on Android 7.0 in multi-window mode

### ISSUE THREAD

**Issue by JonasPrap** [PDF417/pdf417-android#19]
When scanner activity is used in multi-window mode the buttons get misaligned and camera picture is rotated. See photo.

![img_20160830_105639](https://cloud.githubusercontent.com/assets/10437061/18081124/24363dfc-6ea1-11e6-8d28-9e8bd126918a.jpg)

**Comment by DoDoENT** [comment]
This is a known issue - in multi window mode activity gets info that it is in landscape, while being in portrait - this then causes improper rotation of camera preview (proper if device would be really in landscape). We are currently investigating how to detect when device is really in landscape vs when activity only reports being in landscape while actually being in multi-window portrait (different transformation operation on camera view have to be performed in those cases - camera always outputs picture in landscape right orientation, regardless of device's/activity's orientation).

We hope we will have this fixed until official release of Android 7.0.

**Comment by JonasPrap** [comment]
Isn't it already officially released? :) (https://android.googleblog.com/2016/08/android-70-nougat-more-powerful-os-made.html)

It's good that you are working on the fix, just wanted to report it in case you were not aware of the issue.

**Comment by DoDoENT** [comment]
Hi @JonasPrap, apparently there is no easy fix for that issue. It appears to be a [defect in Android API](https://code.google.com/p/android/issues/detail?id=230984&q=orientation%20multi-window&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened) which I reported to Google after not finding [any way to robustly detect correct activity orientation while in multi-window mode](https://stackoverflow.com/questions/41304917/how-to-determine-correct-activity-orientation-in-android-n-multi-window-mode).

For now we will stick with recommendation for our users to completely disable multi-window support for apps using our SDKs (official camera app also has this disabled).

**Comment by DoDoENT** [comment]
This should now be fixed in [v6.1.0](https://github.com/PDF417/pdf417-android/releases/tag/v6.1.0). Please close the issue if it is fixed for you.

**Comment by JonasPrap** [comment]
We will not be switching to 6.0 in the upcoming months, so it will take a while before I can verify this.

**Comment by DoDoENT** [comment]
Why are you not switching to v6.1.0? It's got much improved camera management support.

**Comment by JonasPrap** [comment]
Seems to be working with 6.2.0
