### ISSUE TITLE
Autofocus fail on android

### ISSUE THREAD

**Issue by fetchaquote** [PDF417/pdf417-android#2]
If Pdf417ScanActivity is launched and searching for barcodes and if the camera is occluded for 30 or so seconds, then application crashes and reports the following error:

11-18 17:35:52.494: E/AndroidRuntime(24582): java.lang.RuntimeException: Cannot find resource AutofocusFail in group string for package com.fetch (a.k.a. R.string.AutofocusFail)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at net.photopay.util.FakeR.getId(line:24)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at net.photopay.activity.BaseScanActivity.onAutofocusFailed(line:566)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at net.photopay.view.BaseCameraView.onAutofocusFailed(line:821)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at net.photopay.hardware.camera.focus.llIIlIlIIl$2.onAutoFocus(line:278)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1129)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at android.os.Looper.loop(Looper.java:135)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at java.lang.reflect.Method.invoke(Native Method)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
11-18 17:35:52.494: E/AndroidRuntime(24582): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by DoDoENT** [comment]
Fixed
