### ISSUE TITLE
Unable to parse sample Arkansas USDL

### ISSUE THREAD

**Issue by JonasPrap** [PDF417/pdf417-android#20]
Unable to scan/parse Arkansas license from here: http://dcm.uhcl.edu/caps7g8/Drivers%20License.pdf

Reproduced on 5.5.2 library version and on current BlinkID Scanner app from Google Play.

**Comment by DoDoENT** [comment]
Thank you for your report. Problematic barcodes have been sent to our core development team and they will analyse them and hopefully find and fix the problem.

**Comment by DoDoENT** [comment]
Hi! Does this problem persist in [v6.1.0](https://github.com/PDF417/pdf417-android/releases/tag/v6.1.0)?

**Comment by JonasPrap** [comment]
Apparently you removed support for USDL parser in 6.0.0 so this is no longer relevant in pdf417 library. 

BlinkId Scanner app in google play has not been updated since 2016 may, and it does not scan Arkansas license. So it still has this issue.

**Comment by DoDoENT** [comment]
For customers that have bought PDF417 license prior v6.0.0 release we give the ability to use USDL parser in post v6.0.0 version - so you can try. Also, I am currently working on an update of play store app with latest SDK.

**Comment by JonasPrap** [comment]
And what is the long-term strategy for this? Will pdf417 always have USDL parser for old customers, or will we eventually need to upgrade to BlinkID?

**Comment by DoDoENT** [comment]
For the time being it will have the USDL for old customers. In long terms, we plan to completely remove it, but we first need to ensure that users that require only USDL/barcode features do not get much larger app when integrating BlinkID.

**Comment by JonasPrap** [comment]
Seems to be working with 6.2.0.
