### ISSUE TITLE
error combining pdf417 and blinkid (android)

### ISSUE THREAD

**Issue by mburumaxwell** [PDF417/pdf417-android#34]
I have a project which makes use of both blinkid and pdf417 libraries. It works fine when debugging on an emulator or connected device but when building a final apk, I get the following error
```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/microblink/activity/BaseScanActivity$10;
```

My gradle files looks like under the dependencies section:
```
    compile("com.microblink:blinkid:3.8.1@aar") {
        transitive = true
    }
    compile('com.microblink:pdf417.mobi:6.4.0@aar') {
        transitive = true
        exclude group: 'com.microblink'
    }
```

Is there a solution for this?

**Comment by DoDoENT** [comment]
PDF417 SDK is subset of BlinkID. You can simply use BlinkID SDK (it contains all features present in PDF417 SDK).
