### ISSUE TITLE
Failed to resolve: com.microblink:pdf417.mobi:7.0.0

### ISSUE THREAD

**Issue by alexandersokol** [PDF417/pdf417-android#36]
Hello!
So, I can't even sync your sample projects gradle can't find dependencies to library.
Also the same issues with previous 6.4.0 version

**Comment by culoi** [comment]
Hi @alexandersokol 

First, you need to add maven to repositories list in your build.gradle:

>repositories {
	maven { url 'http://maven.microblink.com' }
}

Then add PDF417 as dependencie:

>dependencies {
    implementation('com.microblink:pdf417.mobi:7.0.0@aar') {
    	transitive = true
    }
}

You can also check out our readme for more info: https://github.com/PDF417/pdf417-android#-integrating-pdf417mobi-into-your-project-using-maven

Regards

**Comment by alexandersokol** [comment]
It does't work it.
The same issue I have when I'm trying to compile samples.

**Comment by culoi** [comment]
Hi @alexandersokol 

Can you please provide a bit more details?

Which error do you get? Is it working from the terminal/command prompt?

The version of the Android Studio and Gradle that you are you using?

Regards

**Comment by alexandersokol** [comment]
Android Studio: 3.0.1
Gradle Plugin Version: 3.0.1
top level build.gradle file:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'http://maven.microblink.com' }
    }
}
```

dependency in app module build.gradle file:

```
    implementation('com.microblink:pdf417.mobi:7.0.0@aar') {
        transitive = true
    }
```

Console error output:

```
> Could not find com.microblink:pdf417.mobi:7.0.0.
  Searched in the following locations:
      file:/home/alex/App/android-sdk/extras/m2repository/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.pom
      file:/home/alex/App/android-sdk/extras/m2repository/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.aar
      file:/home/alex/App/android-sdk/extras/google/m2repository/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.pom
      file:/home/alex/App/android-sdk/extras/google/m2repository/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.aar
      file:/home/alex/App/android-sdk/extras/android/m2repository/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.pom
      file:/home/alex/App/android-sdk/extras/android/m2repository/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.aar
      https://dl.google.com/dl/android/maven2/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.pom
      https://dl.google.com/dl/android/maven2/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.aar
      https://jcenter.bintray.com/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.pom
      https://jcenter.bintray.com/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.aar
      https://maven.fabric.io/public/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.pom
      https://maven.fabric.io/public/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.aar
      http://dl.bintray.com/record360/maven/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.pom
      http://dl.bintray.com/record360/maven/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.aar
      http://maven.microblink.com/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.pom
      http://maven.microblink.com/com/microblink/pdf417.mobi/7.0.0/pdf417.mobi-7.0.0.aar
  Required by:
      project :app
```

**Comment by DoDoENT** [comment]
Hi @alexandersokol , we were having some issues with our maven server and it went offline. The sync should work now. In case you still have problems, you can perform offline AAR integration as described [here](https://github.com/PDF417/pdf417-android#quickIntegration).

We are sorry for the inconvenience.

**Comment by culoi** [comment]
Hello @alexandersokol 

Looks like our maven.microblink.com repo is down as we are doing major website upgrade.

Now should be up and running.

I can also suggest that you use integration from .aar.

**Comment by alexandersokol** [comment]
Thank you guys!
Everything works fine now.

Unfortunately, I can't use AAR lib cause I need another lib which uses this one through maven..
