### ISSUE TITLE
How can I enable the sound?

### ISSUE THREAD

**Issue by dahiandrea** [PDF417/pdf417-android#37]
When I scanned something I want to hear the sound beep. Thank you :)

**Comment by culoi** [comment]
Hello @dahiandrea

If you want sound to be played after the scanning process ends:
        intent.putExtra(Pdf417ScanActivity.EXTRAS_BEEP_RESOURCE, R.raw.beep);

Or you can optionally put here the resource ID of your sound file.

Regards
