### ISSUE TITLE
GenericGFPolys do not have same GenericGF field

### ISSUE THREAD

**Issue by JonasPrap** [PDF417/pdf417-android#9]
It has trouble scanning simple QR codes. For example on this image 

http://cdnqrcgde.s3-eu-west-1.amazonaws.com/wp-content/uploads/2013/11/jpeg.jpg

It keeps throwing error logs:

```
01-08 10:16:34.449  17475-18921/com.xxx E/ZXingReader.cpp:145﹕ illegal argument exception: GenericGFPolys do not have same GenericGF field
01-08 10:16:35.809  17475-18921/com.xxx E/ZXingReader.cpp:145﹕ illegal argument exception: GenericGFPolys do not have same GenericGF field
01-08 10:16:37.059  17475-18921/com.xxx E/ZXingReader.cpp:145﹕ illegal argument exception: GenericGFPolys do not have same GenericGF field
01-08 10:16:37.269  17475-18921/com.xxx E/ZXingReader.cpp:145﹕ illegal argument exception: GenericGFPolys do not have same GenericGF field
```

Only after ~10 seconds it manages to scan the QR code

**Comment by Cerovec** [comment]
Hi Jonas,

internal exceptions are completely harmless, they won't cause a crash or anything. If they bother you, we can silence them completely.

For troubles with scanning this specific QR code:
1) Which Android device were you using?
2) Were you scanning from screen or printed code?
3) What was the distance between the device and the barcode?
4) Can you send us a screenshot which shows how the use case where code cannot be scanned?

This will help is in creating a fix as soon as possible.

Thanks!
Jurica.

**Comment by JonasPrap** [comment]
1) Galaxy S5, Android 4.4.2
2) Screen
3) Approx 30cm (see photo)

It scans the barcode fine when I hold phone straight to it, but this angle somehow makes it not recognize the barcode. It just keeps blinking those green dots and throws lots of mentioned error in logs.  Autofocus does work fine.

I reported this as it was a surprise it did not scan this quickly when zbar has no problem with it in exact same conditions.

![imag0692](https://cloud.githubusercontent.com/assets/10437061/5662007/8d169e14-973b-11e4-9960-65c9ee557e3c.jpg)


```
                Pdf417MobiSettings sett = new Pdf417MobiSettings();
                sett.setAll1DBarcodesEnabled(true);
                sett.setAll2DBarcodesEnabled(true);
                sett.setPdf417Enabled(false);
                sett.setDontShowDialog(true);

                Intent intent = new Intent(FormActivity.this, Pdf417ScanActivity.class);
                intent.putExtra(Pdf417ScanActivity.EXTRAS_SETTINGS, sett);
                startActivityForResult(intent, PDF417MOBI_INTENT_KEY);
```

**Comment by Cerovec** [comment]
Thanks for the explanation.

The difference exists probably because zbar uses a scanning region (a rectangle in which the barcode should be placed), to make the scanning area smaller, and to force the user to position the barcode in an angle better suited for scanning.

You can implement scanning region in pdf417 SDK as well. Search the documentation for text "if you want to set scanning region, you can do it in the following way:"

In version 4.0 we are planning an additional algorithm which will improve QR code scanning when scanning region is NOT used.

PS. If you're interested only in QR code scanning, use the following settings to obtain faster results:

    sett.setAll1DBarcodesEnabled(false);
    sett.setAll2DBarcodesEnabled(false);
    sett.setQrCodeEnabled(true);
